services:
  Purchasehistory\Form\Modifier\ProductFormModifier:
    autowire: true
    public: true
    arguments:
      $formBuilderModifier: '@form.form_builder_modifier'

  prestashop.module.purchasehistory.product_page_tab:
    class: Purchasehistory\Form\Type\PurchaseHistoryTabType
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      $translator: '@translator.default'
      $locales: '@=service("prestashop.adapter.legacy.context").getLanguages()'
      $repository: '@prestashop.module.purchasehistory.purchasehistory_repository'
    tags:
      - { name: form.type }

  prestashop.module.purchasehistory.purchasehistory_repository:
    class: Purchasehistory\Repository\PurchaseHistoryRepository
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
    autowire: true
    public: true
