services:
  Purchasehistory\Form\Modifier\ProductFormModifier:
    autowire: true
    public: true
    arguments:
      $formBuilderModifier: '@form.form_builder_modifier'

  prestashop.module.purchasehistory.product_page:
    class: Purchasehistory\Form\Type\CustomTabType
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      $translator: '@translator.default' # TranslatorInterface
      $locales: '@=service("prestashop.adapter.legacy.context").getLanguages()' # Локалі
      $repository: '@prestashop.module.purchasehistory.purchasehistory_repository' # PurchaseHistoryRepository
      $twig: '@twig' # Environment
    tags:
      - { name: form.type }

  prestashop.module.purchasehistory.purchasehistory_repository:
    class: Purchasehistory\Repository\PurchaseHistoryRepository
    autowire: true
    public: true